kind: pipeline
name: run-python-script

trigger:
  event:
    - push          # Trigger on push events
    - pull_request  # Trigger on pull requests
  branch:
    - main          # Only trigger for changes to the 'main' branch

steps:
  - name: setup python environment
    image: python:3.8  # Use an image with Python 3.8
    commands:
      - python --version  # Verify the Python version is correct

  - name: run python script
    image: python:3.8  # Use an image with Python 3.8 to execute the script
    commands:
      - python pythontest.py  # Run the Python script