name: Python CI

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the environment

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (you can specify the version you need, e.g., 3.9, 3.10, etc.)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version (adjust as needed)

      # Install dependencies (if any are specified in a requirements.txt file)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if you're using a different package manager

      # Run your Python file (replace 'your_script.py' with the name of your Python file)
      - name: Run Python script
        run: |
          python Hello.py  # Replace with your script filename
